[package]
name = "origin-pingora"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.78"
chrono = "0.4.35"
http = "1.1.0"
pingora = "0.1.0"
tokio = "1.36.0"
