[package]
name = "hello-pingora-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.78"
bytes = "1.6.0"
http = "1.1.0"
pingora = "0.1.0"
