[package]
name = "origin-actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "3.6.0"
actix-rt = "2.9.0"
actix-server = "2.3.0"
env_logger = "0.11.3"
tracing = "0.1.40"
