[package]
name = "proxy-actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
awc = "3.4.0"
env_logger = "0.11.3"
tracing = "0.1.40"
url = "2.5.0"
